version: '3'

services:

  vulnSrv:
    build:
      context: .
      dockerfile: Dockerfile.vuln
    image: debian:min-dop-vuln
    container_name: min-dop-vuln
    working_dir: /repo
    volumes:
      - ${REPO_PATH}:/repo
    tty: true
  hardenedSrv:
    build:
      context: .
      dockerfile: Dockerfile.hardened
    image: debian:min-dop-hardened
    container_name: min-dop-hardened
    working_dir: /repo
    volumes:
      - ${REPO_PATH}:/repo
    tty: true
